### ISSUE TITLE
lost my UST when moving from Harmony to Terra using terra bridge

### ISSUE THREAD

**Issue by CryptoHasMuscle** [terra-money/bridge-web-app#114]
Before Harmony's network shut down couple days ago, I sent UST to my terra wallet but it didn't get there or return back to my harmony wallet. 

Here is the transaction ID: https://explorer.harmony.one/tx/0xd4e41ac4c398f2f3045e6913d4522ebadfcf5c04c7d2797350ec21fed3fa8107?activeTab=0

I have been bridging UST from Harmony to Terra for some days and didn't have this issue before. Appreciate if someone can look into it and restore my UST.

**Comment by MarkXZZ** [comment]
same problem，I lost my UST when moving from Harmony to Terra using terra bridge.
https://explorer.harmony.one/tx/0x6103fd41aa0680d471d635a35c1a83cbc3c901c37f50b102743b34f46437dce6?activeTab=2
I just tried a transaction and it worked.
Yesterday's transaction still not received

**Comment by cryptopunks6690** [comment]
Hello @CryptoHasMuscle   , You should talk to a Terra money Dev on the [Live support page](https://agoraterra.org/). So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.org/)

**Comment by alecande11** [comment]
@CryptoHasMuscle sorry for the late response, have you solved now?

**Comment by CryptoHasMuscle** [comment]
Not yet. The fund are still lost in bridge

**Comment by CryptoHasMuscle** [comment]
Please take a look at the truncations if you can help. Someone was trying to scam me here earlier, directing me to a fake terra website....

[https://explorer.harmony.one/tx/0xd4e41ac4c398f2f3045e6913d4522ebadfcf5c04c7d2797350ec21fed3fa8107?activeTab=0]()

[https://explorer.harmony.one/tx/0x80029062536ef090dda9b9302634d2c7ba7e4d303200c415705804b11e93f34d]()

**Comment by CryptoHasMuscle** [comment]
Someone was trying to scam me so I'm not sure if you are legit or not.

The problem is not solved yet. The funds are lost in bridge in these two
transactions:

https://explorer.harmony.one/tx/0x80029062536ef090dda9b9302634d2c7ba7e4d303200c415705804b11e93f34d

https://explorer.harmony.one/tx/0xd4e41ac4c398f2f3045e6913d4522ebadfcf5c04c7d2797350ec21fed3fa8107?activeTab=0

**Comment by alecande11** [comment]
Yeah, sorry for the scammers, you can see that I'm from TerraForm Labs from my GitHub profile.
I've fill out a recover request for you, in a few minutes you should see your UST on your terra wallet

**Comment by CryptoHasMuscle** [comment]
Thanks a lot! Saw the fund! You are so helpful!
